In [1]:
from sklearn.datasets import fetch_openml

# X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
# X = X.values
# y = y.astype(int).values
# 
# print(X.shape)
# print(y.shape)

In [2]:
import numpy as np
import torch

print('PyTorch version:', torch.__version__)

np.set_printoptions(precision=3)

PyTorch version: 1.13.1


## Creating tensors in Pytorch

In [3]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [4]:
t_a.dtype

torch.int64

In [5]:
torch.is_tensor(a), torch.is_tensor(t_a)

(False, True)

In [6]:
t_ones = torch.ones(2, 3)
t_ones.shape

torch.Size([2, 3])

## Manipulating the data type and shape of a tensor

In [7]:
t_a_new = t_a.to(torch.int64)

In [8]:
t = torch.rand(3, 5)
t_tr = torch.transpose(t, 0, 1)

## Creating a Pytorch DataLoader from existing tensors

In [9]:
from torch.utils.data import DataLoader

t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t)

for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [10]:
data_loader = DataLoader(t, batch_size=3, drop_last=False)

for i, batch in enumerate(data_loader, 1):
    print(f'batch {i}:', batch)

batch 1: tensor([0., 1., 2.])
batch 2: tensor([3., 4., 5.])


### Combining two tensors into a joint dataset

In [11]:
from torch.utils.data import Dataset

class JointDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]
    
    def __len__(self):
        return len(self.x)

In [12]:
torch.manual_seed(1)

t_x = torch.rand([4, 3], dtype=torch.float32)
t_y = torch.arange(4)
joint_dataset = JointDataset(t_x, t_y)

# Or use TensorDataset directly
from torch.utils.data import TensorDataset
joint_dataset = TensorDataset(t_x, t_y)

for example in joint_dataset:
    print('  x: ', example[0],
          '  y: ', example[1])

  x:  tensor([0.7576, 0.2793, 0.4031])   y:  tensor(0)
  x:  tensor([0.7347, 0.0293, 0.7999])   y:  tensor(1)
  x:  tensor([0.3971, 0.7544, 0.5695])   y:  tensor(2)
  x:  tensor([0.4388, 0.6387, 0.5247])   y:  tensor(3)


In [14]:
torch.manual_seed(1)
data_loader = DataLoader(dataset=joint_dataset, shuffle=True, batch_size=2)

for i, batch in enumerate(data_loader, 1):
    print(f'batch {i}:', 'x:', batch[0], '\n         y:', batch[1])

batch 1: x: tensor([[0.3971, 0.7544, 0.5695],
        [0.7576, 0.2793, 0.4031]]) 
         y: tensor([2, 0])
batch 2: x: tensor([[0.7347, 0.0293, 0.7999],
        [0.4388, 0.6387, 0.5247]]) 
         y: tensor([1, 3])
