In [1]:
import torch
import numpy as np
np.set_printoptions(precision=3)
a = [1, 2,3]
b = np.array([4,5,6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a), print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


(None, None)

In [11]:
t_b = torch.tensor(b)
t_b

tensor([4, 5, 6], dtype=torch.int32)

In [2]:
t_a.dtype

torch.int64

In [3]:
t_ones = torch.ones((2, 3))
t_ones.shape

torch.Size([2, 3])

In [4]:
t_ones.shape[0]

2

In [5]:
# 转置
t = torch.rand(3, 5)
t_tr = torch.transpose(t, 0, 1)

In [6]:
t

tensor([[0.6555, 0.5606, 0.1375, 0.8693, 0.1350],
        [0.5500, 0.7376, 0.5952, 0.3875, 0.4394],
        [0.2165, 0.5030, 0.1008, 0.3498, 0.7542]])

In [7]:
t.transpose(0, 1)

tensor([[0.6555, 0.5500, 0.2165],
        [0.5606, 0.7376, 0.5030],
        [0.1375, 0.5952, 0.1008],
        [0.8693, 0.3875, 0.3498],
        [0.1350, 0.4394, 0.7542]])

In [8]:
t = torch.zeros(30)
t_reshape = t.reshape(5, 6) # 或torch.reshape(t, (5, 6))
t_reshape

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [9]:
torch.reshape(t, (5, 6))

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [10]:
# Removing the unnecessary dimensions:
t = torch.zeros(1, 2, 1, 4, 1)
torch.squeeze(t, 2), t.squeeze(2)   # torch.Size([1, 2, 1, 4, 1])  -->  torch.Size([1, 2, 4, 1])

(tensor([[[[0.],
           [0.],
           [0.],
           [0.]],
 
          [[0.],
           [0.],
           [0.],
           [0.]]]]),
 tensor([[[[0.],
           [0.],
           [0.],
           [0.]],
 
          [[0.],
           [0.],
           [0.],
           [0.]]]]))